apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
   app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: vprofile/vprofiledb:V1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3386
          name: vprodb-port
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vprodb-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-pass
              name: app-secret
      volumes: 
        - name: vprodb-data
          hostPath: 
            path: /home/vagrant/pract/mysql-data
            type: DirectoryOrCreate
       
