apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprorabbit
  labels:
    app: vprorabbit
spec:
  selector:
    matchLabels:
      app: vprorabbit
  template:
    metadata:
      labels:
        app: vprorabbit
    spec:
      containers:
      - name: vprorabbit
        image: rabbitmq
        ports:
        - containerPort: 15672
          name: vprorabbit-port
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: db-pass
              name: rmq-secret
        - name: RABBITMQ_DEFAULT_USER
          valueFrom: "guest"
